package com.mhd.accountManagement.model.Enums;

public enum DoctorSpecialty {
    GENERAL_PRACTITIONER,
    CARDIOLOGIST,
    DERMATOLOGIST,
    NEUROLOGIST,
    ORTHOPEDIC_SURGEON,
    PEDIATRICIAN,
    PSYCHIATRIST,
    RADIOLOGIST,
    ONCOLOGIST,
    GYNECOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    OPHTHALMOLOGIST,
    ENT_SPECIALIST,
    PULMONOLOGIST,
    NEPHROLOGIST,
    UROLOGIST,
    RHEUMATOLOGIST,
    HEMATOLOGIST,
    INFECTIOUS_DISEASE_SPECIALIST,
    PLASTIC_SURGEON,
    DENTIST
}
